// Fixed slots prevent the public endpoint being used for arbitrary API searches.
export const imageQueries = {
  'dbf-hero': 'countryside villa garden',
  'dbf-luxury-pool': 'villa swimming pool',
  'dbf-eco-nature': 'lush green garden',
  'dbf-welcome-gift': 'welcome gift basket',
  'dbf-chef-dining': 'outdoor dining table',
  'dbf-villa-ext': 'countryside villa exterior',
  'dbf-suites-lux': 'luxury bedroom',
  'dbf-celebration-lawn': 'garden wedding venue',
  'dbf-dining-gourmet': 'gourmet dinner',
  'dbf-event-wedding': 'indian wedding decoration',
  'dbf-event-retreat': 'team outdoor gathering',
  'dbf-event-birthday': 'garden birthday party',
  'dbf-event-wellness': 'outdoor yoga',
  'dbf-about-head': 'countryside garden',
  'dbf-story': 'country house garden',
  'dbf-vision': 'nature landscape garden',
  'dbf-stay-head': 'villa bedroom',
  'dbf-s1': 'bedroom garden view',
  'dbf-s2': 'poolside villa room',
  'dbf-events-head': 'outdoor wedding venue',
  'dbf-wed': 'indian wedding decoration',
  'dbf-party': 'pool party',
  'dbf-corp': 'team outdoor gathering',
  'dbf-l1': 'garden wedding lawn',
  'dbf-p1': 'villa swimming pool',
  'dbf-c2': 'banquet hall',
  'dbf-dining-head': 'luxury restaurant terrace',
  'dbf-facilities-head': 'resort swimming pool amenities',
  'dbf-birthday-head': 'garden birthday party celebration',
  'dbf-weddings-head': 'royal indian wedding decoration',
  'dbf-pool-party-head': 'villa pool party summer',
  'dbf-policy-head': 'luxury hotel lounge',
};
